server.port=8888

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.open-in-view=false


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=10000


logging.file.name=logs/ideal-atendimento.log

app.jwt.keystore-location=keys/keystore.jks
app.jwt.keystore-password=..suporte2020
app.jwt.key-alias=jwtsigning
app.jwt.private-key-passphrase=..suporte2020
app.jwt.validity-in-seconds=28800

