server.port=8888

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.open-in-view=false


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=10000


logging.file.name=logs/ideal-atendimento.log

app.jwt.keystore-location=keys/keystore.jks
app.jwt.keystore-password=..suporte2020
app.jwt.key-alias=jwtsigning
app.jwt.private-key-passphrase=..suporte2020
app.jwt.validity-in-seconds=28800


aplicacao.maxdata.base-url=http://localhost:8888

aplicacao.storage.root=/home/carlos/work/ideal/storage
aplicacao.storage.anexos-dir=anexos


aplicacao.n8n.hook-url=http://172.16.98.14:5678/webhook/52577a3e-64c2-41e8-b94a-585d1eb02169


aplicacao.wppconnectserver.base-url=http://localhost:21465/api/wppsession
aplicacao.wppconnectserver.token=$2b$10$cPolPbgWypz6F5FBvD_z8ebZDp58X0J.JHtDJ0DjKVVvLvW_h9TIW


spring.cache.type=caffeine
spring.cache.cache-names=dashboard
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=30s

spring.flyway.placeholder-replacement=false